version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: todo

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./todo:/app/todo
      - ./credentials:/root/.aws/credentials
    env_file: "aws.env"
    environment:
      CELERY_BROKER_URL: sqs://
    ports:
      - "6400:6400"
    depends_on:
      - database

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file: "aws.env"
    environment:
      CELERY_BROKER_URL: sqs://
    command: poetry run celery --app todo.tasks.ical worker --loglevel=info
